Ruthvik Prashant Patil
44
Batch 3 
12210258

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/home/ruthvik/Downloads/tennis.csv')

In [3]:
data

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [4]:
data['play'].value_counts()

play
yes    9
no     5
Name: count, dtype: int64

In [5]:
#probabilty of yes and no

Pyes = 9/14
Pno = 5/14

In [6]:
print(Pyes)
print(Pno)

0.6428571428571429
0.35714285714285715

In [7]:
#lets create a outlook table, finding probabilities in each case.
#column = outlook

pd.crosstab(data['outlook'],data['play'])

play      no  yes
outlook
overcast   0    4
rainy      2    3
sunny      3    2

In [8]:
#probabilities

PsunnyNo = 3/5
PrainyNo = 2/5
PovercastNo = 0

PsunnyYes = 2/9
PrainyYes = 3/9
PovercastYes = 4/9

In [9]:
#column = temp

pd.crosstab(data['temp'],data['play'])

play  no  yes
temp
cool   1    3
hot    2    2
mild   2    4

In [10]:
#probabilities

PcoolNo = 1/5
PhotNo = 2/5
PmildNo = 2/5

PcoolYes = 3/9
PhotYes = 2/9
PmildYes = 4/9

In [11]:
#column = humidity

pd.crosstab(data['humidity'],data['play'])

play      no  yes
humidity
high       4    3
normal     1    6

In [12]:
#probabilities

PhighNo = 4/5
PnormalNo = 1/5

PhighYes = 3/9
PnormalYes = 6/9

In [13]:
#column = windy
#true = strong wind , false = weak wind

pd.crosstab(data['windy'],data['play'])

play   no  yes
windy
False   2    6
True    3    3

In [14]:
#probabilities

PweakNo = 2/5
PstrongNo = 3/5

PweakYes = 6/9
PstrongYes = 3/9

In [15]:
#calculating the probabilty of yes for outlook = sunny , temp = hot , humidity = high , wind = weak
#P(yes/sunny, hot, high, weak) = P(sunny/yes)*P(hot/yes)*P(high/yes)*P(weak/yes)*P(yes)


Prob_yes = PsunnyYes*PhotYes*PhighYes*PweakYes*Pyes
print("probabilty of Yes  : ", Prob_yes)

Prob_no = PsunnyNo*PhotNo*PhighNo*PweakNo*Pno
print("probabilty of No  : ", Prob_no)

probabilty of Yes  :  0.007054673721340387
probabilty of No  :  0.02742857142857143

**Conclusion**: Since the Probability of No is greater than yes. Naive Bayes will say **NO PLAY**.